name: Update Feeds

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
      timezone: "Asia/Tehran"

jobs:
  update-feeds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      
      - name: setting up
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: installing dependencies
        run: pip install requests

      - name: run script
        run: python Scripts/main.py

      - name: commit changes
        uses: EndBug/add-and-commit@v10
        with:
          author_name: Shawn Kasaei
          author_email: shayakasaei@gmail.com
          force: false
          signoff: false
          message: ":memo: FEED updated by Shawn"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
