name: Update Schedule

permissions:
  contents: write

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"
      timezone: "Asia/Tehran"

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v6
      
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script
        run: python Scripts/main.py

      - name: commit changes
        uses: EndBug/add-and-commit@v10
        with:
          author_name: Shawn Kasaei
          author_email: shayakasaei@gmail.com
          force: false
          signoff: false
          message: "Schedule: feed updated"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
